version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"